const API='http://localhost:3000';
const $=id=>document.getElementById(id);
const money=n=>'₹'+Number(n).toLocaleString('en-IN');
const escapeHTML=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const getCart=()=>JSON.parse(localStorage.getItem('novacart_cart')||'[]');
const getUser=()=>JSON.parse(localStorage.getItem('novacart_user')||'null');
function saveCart(cart){localStorage.setItem('novacart_cart',JSON.stringify(cart));updateCount()}
function updateCount(){if($('cart-count'))$('cart-count').textContent=getCart().reduce((n,x)=>n+x.quantity,0)}
function message(text,error=false){if($('message')){$('message').textContent=text;$('message').className='message'+(error?' error':'')}}
async function products(){return (await axios.get(API+'/products')).data}
function card(p){return `<article class="product-card"><div class="product-badge">POPULAR PICK</div><a href="product-details.html?id=${p.id}"><img loading="lazy" src="${escapeHTML(p.image)}" alt="${escapeHTML(p.name)}"></a><div class="product-info"><span class="muted">${escapeHTML(p.category)}</span><h3><a href="product-details.html?id=${p.id}">${escapeHTML(p.name)}</a></h3><p class="rating">★ ${p.rating}</p><p class="price">${money(p.price)}</p><button class="btn" onclick="addToCart(${Number(p.id)})" ${p.stock<1?'disabled':''}>${p.stock<1?'Out of stock':'Add to Cart'}</button></div></article>`}
async function addToCart(id){try{const p=(await axios.get(API+'/products/'+id)).data;const cart=getCart();let item=cart.find(x=>x.id===p.id);if((item?.quantity||0)>=p.stock){message('Not enough stock',true);return}if(item)item.quantity++;else cart.push({id:p.id,name:p.name,price:p.price,image:p.image,quantity:1});saveCart(cart);message('Added to cart!')}catch(e){message('Could not add product. Start JSON Server.',true)}}
async function home(){try{$('featured').innerHTML=(await products()).slice(0,4).map(card).join('')}catch(e){message('Start JSON Server using npm start.',true)}}
let all=[];
async function listProducts(){try{all=await products();let params=new URLSearchParams(location.search);let category=params.get('category');if(params.get('q'))$('search').value=params.get('q');if(category)$('category').value=category;filterProducts();['search','category','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',filterProducts))}catch(e){message('Could not load products. Check JSON Server.',true)}}
function filterProducts(){let q=$('search').value.toLowerCase().trim(),cat=$('category').value,sort=$('sort').value;let items=all.filter(p=>(p.name.toLowerCase().includes(q)||p.description.toLowerCase().includes(q))&&(cat==='All'||p.category===cat));if(sort==='low')items.sort((a,b)=>a.price-b.price);if(sort==='high')items.sort((a,b)=>b.price-a.price);if(sort==='rating')items.sort((a,b)=>b.rating-a.rating);if($('result-count'))$('result-count').textContent=items.length+' product'+(items.length===1?'':'s')+' found';$('product-list').innerHTML=items.length?items.map(card).join(''):'<div class="empty">No products found. Try another search or category.</div>'}
async function details(){let id=new URLSearchParams(location.search).get('id');if(!/^\d+$/.test(id||'')){message('Invalid product ID',true);return}try{let p=(await axios.get(API+'/products/'+id)).data;$('product-details').innerHTML=`<div class="details-layout"><img src="${escapeHTML(p.image)}" alt="${escapeHTML(p.name)}"><div class="details-info"><span class="muted">${escapeHTML(p.category)}</span><h1>${escapeHTML(p.name)}</h1><p class="rating">★ ${p.rating} / 5</p><p class="price">${money(p.price)}</p><p>${escapeHTML(p.description)}</p><p class="stock">${p.stock} available</p><button class="btn" onclick="addToCart(${Number(p.id)})" ${p.stock<1?'disabled':''}>Add to Cart</button><p><a href="products.html">← Back to Products</a></p></div></div>`}catch(e){message('Product not found',true)}}
function renderCart(){let cart=getCart();$('cart-items').innerHTML=cart.length?cart.map(x=>`<article class="cart-item"><img src="${escapeHTML(x.image)}" alt="${escapeHTML(x.name)}"><div class="cart-info"><h3>${escapeHTML(x.name)}</h3><p class="price">${money(x.price)}</p><div class="quantity"><button onclick="changeQty(${Number(x.id)},-1)">−</button><strong>${x.quantity}</strong><button onclick="changeQty(${Number(x.id)},1)">+</button></div><button class="remove" onclick="removeItem(${Number(x.id)})">Remove</button></div></article>`).join(''):'<div class="empty"><h2>Your cart is empty</h2><p>Add some products to get started.</p><p><a class="btn" href="products.html">Shop Now</a></p></div>';let subtotal=cart.reduce((n,x)=>n+x.price*x.quantity,0),delivery=subtotal>0&&subtotal<999?99:0;$('subtotal').textContent=money(subtotal);$('delivery').textContent=money(delivery);$('total').textContent=money(subtotal+delivery);$('checkout').disabled=!cart.length}
async function changeQty(id,delta){let cart=getCart(),item=cart.find(x=>x.id===id);if(!item)return;if(delta>0){try{let p=(await axios.get(API+'/products/'+id)).data;if(item.quantity>=p.stock){message('Not enough stock',true);return}}catch(e){message('Cannot check stock',true);return}}item.quantity+=delta;saveCart(cart.filter(x=>x.quantity>0));renderCart()}
function removeItem(id){saveCart(getCart().filter(x=>x.id!==id));renderCart();message('Product removed')}
async function checkout(){let user=getUser();if(!user){alert('Please login first');location.href='login.html';return}let cart=getCart();if(!cart.length)return;$('checkout').disabled=true;try{let available=await products();for(let item of cart){let p=available.find(x=>x.id===item.id);if(!p||p.stock<item.quantity){message(item.name+' is out of stock',true);return}}let items=cart.map(x=>{let p=available.find(y=>y.id===x.id);return {productId:p.id,name:p.name,price:p.price,quantity:x.quantity}});let subtotal=items.reduce((n,x)=>n+x.price*x.quantity,0);let order={userId:user.id,items,subtotal,delivery:subtotal>=999?0:99,total:subtotal+(subtotal>=999?0:99),status:'Placed',date:new Date().toISOString()};let result=await axios.post(API+'/orders',order);for(let item of items){let p=available.find(x=>x.id===item.productId);await axios.patch(API+'/products/'+p.id,{stock:p.stock-item.quantity})}saveCart([]);renderCart();message('Demo order #'+result.data.id+' placed successfully!')}catch(e){message('Could not complete order. Check the orders database before retrying.',true)}finally{$('checkout').disabled=!getCart().length}}
async function register(e){e.preventDefault();let name=$('name').value.trim(),email=$('email').value.trim().toLowerCase(),password=$('password').value;if(password!==$('confirm').value){message('Passwords do not match',true);return}try{let found=(await axios.get(API+'/users',{params:{email}})).data;if(found.length){message('Email already registered',true);return}await axios.post(API+'/users',{name,email,password});alert('Registered! Please login.');location.href='login.html'}catch(err){message('Registration failed. Check JSON Server.',true)}}
async function login(e){e.preventDefault();let email=$('email').value.trim().toLowerCase(),password=$('password').value;try{let found=(await axios.get(API+'/users',{params:{email}})).data.find(x=>x.password===password);if(!found){message('Invalid email or password',true);return}localStorage.setItem('novacart_user',JSON.stringify({id:found.id,name:found.name,email:found.email}));location.href='index.html'}catch(err){message('Login failed. Check JSON Server.',true)}}
function navigation(){let user=getUser();if(user&&$('login-link')){$('login-link').textContent='Hi, '+user.name;$('login-link').removeAttribute('href')}if(user&&$('logout')){$('logout').classList.remove('hidden');$('logout').onclick=()=>{localStorage.removeItem('novacart_user');location.href='index.html'}}}
document.addEventListener('DOMContentLoaded',()=>{updateCount();navigation();let page=document.body.dataset.page;if(page==='home'||page==='index')home();if(page==='products')listProducts();if(page==='details')details();if(page==='cart'){renderCart();$('checkout').onclick=checkout}if(page==='login')$('login-form').onsubmit=login;if(page==='register')$('register-form').onsubmit=register});
